"""Central color palette inspired by MonkeyType's serika-dark theme."""

ACCENT = "yellow"
PENDING = "grey42"
CORRECT = "white"
INCORRECT = "red"
EXTRA = "#7e2a33"
CURSOR = "black on yellow"
SUBTLE = "grey50"
HEADER = "bold yellow"
